import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:ojekdriver/pages/dashboard_page.dart';
import 'package:ojekdriver/pages/login_page.dart';
import 'package:ojekdriver/services/notification_service.dart';
import 'package:ojekdriver/session/session_manager.dart';
import 'package:toastification/toastification.dart';
import 'firebase_options.dart'; // Ensure this file exists, generated by flutterfire configure

import 'package:ojekdriver/services/location_service.dart';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await NotificationService().initialize();
  // Start location service if already logged in (checked inside service or caller)
  // But here we just ensure it's ready. Actual start happens on login or dashboard init.
  runApp(const SkyGoDriverApp());
}

class SkyGoDriverApp extends StatelessWidget {
  const SkyGoDriverApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ToastificationWrapper(
      child: MaterialApp(
        navigatorKey: navigatorKey,
        title: 'SkyGo Driver',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primaryColor: const Color(0xFF00BFFF),
          scaffoldBackgroundColor: Colors.white,
          fontFamily: 'Roboto', // Default modern font
          colorScheme: ColorScheme.fromSwatch().copyWith(
            secondary: const Color(0xFF87CEEB),
          ),
        ),
        home: const AuthWrapper(),
      ),
    );
  }
}

class AuthWrapper extends StatefulWidget {
  const AuthWrapper({Key? key}) : super(key: key);

  @override
  _AuthWrapperState createState() => _AuthWrapperState();
}

class _AuthWrapperState extends State<AuthWrapper> {
  bool? _isLoggedIn;

  @override
  void initState() {
    super.initState();
    _checkSession();
  }

  void _checkSession() async {
    final isLoggedIn = await SessionManager().isLoggedIn();
    setState(() {
      _isLoggedIn = isLoggedIn;
      if (isLoggedIn) {
        LocationService().startSendingLocation();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoggedIn == null) {
      return const Scaffold(
        body: Center(
          child: CircularProgressIndicator(color: Color(0xFF00BFFF)),
        ),
      );
    }
    return _isLoggedIn! ? const DashboardPage() : const LoginPage();
  }
}
